language: python
python:
    - "3.4"
    - "3.5"
before_install:
    - pip install pytest pytest-cov
install:
    - python setup.py install
before_script:
    - python -m nltk.downloader punkt
    - python -m textblob.download_corpora
script:
    - py.test